// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_izHH-1AiORbOnQb4ijxJSWGwP9McUY',
    appId: '1:771640264524:web:a1cbd1915df47a30feb1e9',
    messagingSenderId: '771640264524',
    projectId: 'tms-learning',
    authDomain: 'tms-learning.firebaseapp.com',
    storageBucket: 'tms-learning.firebasestorage.app',
    measurementId: 'G-HCXYK9FBWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfRcz34Hu_iKYmOmxVGPHx6vUVzD4HOg',
    appId: '1:771640264524:android:32ad6ed8093b90b9feb1e9',
    messagingSenderId: '771640264524',
    projectId: 'tms-learning',
    storageBucket: 'tms-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5mRcbp_J-ddAxoJ1JloupLh4_14EDn1k',
    appId: '1:771640264524:ios:af56cf2eb2ca8fddfeb1e9',
    messagingSenderId: '771640264524',
    projectId: 'tms-learning',
    storageBucket: 'tms-learning.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5mRcbp_J-ddAxoJ1JloupLh4_14EDn1k',
    appId: '1:771640264524:ios:af56cf2eb2ca8fddfeb1e9',
    messagingSenderId: '771640264524',
    projectId: 'tms-learning',
    storageBucket: 'tms-learning.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_izHH-1AiORbOnQb4ijxJSWGwP9McUY',
    appId: '1:771640264524:web:971a78fd23aeaeeefeb1e9',
    messagingSenderId: '771640264524',
    projectId: 'tms-learning',
    authDomain: 'tms-learning.firebaseapp.com',
    storageBucket: 'tms-learning.firebasestorage.app',
    measurementId: 'G-84WYHR1RG6',
  );
}
